// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/cima-server.proto

package cima

import (
        context "context"
        grpc "google.golang.org/grpc"
        codes "google.golang.org/grpc/codes"
        status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
        Cima_GetDefaultAlgorithm_FullMethodName = "/cima_server_pb.cima/GetDefaultAlgorithm"
        Cima_GetMeasurementCount_FullMethodName = "/cima_server_pb.cima/GetMeasurementCount"
        Cima_GetCcReport_FullMethodName         = "/cima_server_pb.cima/GetCcReport"
        Cima_GetCcMeasurement_FullMethodName    = "/cima_server_pb.cima/GetCcMeasurement"
        Cima_GetCcEventlog_FullMethodName       = "/cima_server_pb.cima/GetCcEventlog"
)

// CimaClient is the client API for Cima service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CimaClient interface {
        GetDefaultAlgorithm(ctx context.Context, in *GetDefaultAlgorithmRequest, opts ...grpc.CallOption) (*GetDefaultAlgorithmResponse, error)
        GetMeasurementCount(ctx context.Context, in *GetMeasurementCountRequest, opts ...grpc.CallOption) (*GetMeasurementCountResponse, error)
        GetCcReport(ctx context.Context, in *GetCcReportRequest, opts ...grpc.CallOption) (*GetCcReportResponse, error)
        GetCcMeasurement(ctx context.Context, in *GetCcMeasurementRequest, opts ...grpc.CallOption) (*GetCcMeasurementResponse, error)
        GetCcEventlog(ctx context.Context, in *GetCcEventlogRequest, opts ...grpc.CallOption) (*GetCcEventlogResponse, error)
}

type cimaClient struct {
        cc grpc.ClientConnInterface
}

func NewCimaClient(cc grpc.ClientConnInterface) CimaClient {
        return &cimaClient{cc}
}

func (c *cimaClient) GetDefaultAlgorithm(ctx context.Context, in *GetDefaultAlgorithmRequest, opts ...grpc.CallOption) (*GetDefaultAlgorithmResponse, error) {
        out := new(GetDefaultAlgorithmResponse)
        err := c.cc.Invoke(ctx, Cima_GetDefaultAlgorithm_FullMethodName, in, out, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *cimaClient) GetMeasurementCount(ctx context.Context, in *GetMeasurementCountRequest, opts ...grpc.CallOption) (*GetMeasurementCountResponse, error) {
        out := new(GetMeasurementCountResponse)
        err := c.cc.Invoke(ctx, Cima_GetMeasurementCount_FullMethodName, in, out, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *cimaClient) GetCcReport(ctx context.Context, in *GetCcReportRequest, opts ...grpc.CallOption) (*GetCcReportResponse, error) {
        out := new(GetCcReportResponse)
        err := c.cc.Invoke(ctx, Cima_GetCcReport_FullMethodName, in, out, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *cimaClient) GetCcMeasurement(ctx context.Context, in *GetCcMeasurementRequest, opts ...grpc.CallOption) (*GetCcMeasurementResponse, error) {
        out := new(GetCcMeasurementResponse)
        err := c.cc.Invoke(ctx, Cima_GetCcMeasurement_FullMethodName, in, out, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *cimaClient) GetCcEventlog(ctx context.Context, in *GetCcEventlogRequest, opts ...grpc.CallOption) (*GetCcEventlogResponse, error) {
        out := new(GetCcEventlogResponse)
        err := c.cc.Invoke(ctx, Cima_GetCcEventlog_FullMethodName, in, out, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

// CimaServer is the server API for Cima service.
// All implementations must embed UnimplementedCimaServer
// for forward compatibility
type CimaServer interface {
        GetDefaultAlgorithm(context.Context, *GetDefaultAlgorithmRequest) (*GetDefaultAlgorithmResponse, error)
        GetMeasurementCount(context.Context, *GetMeasurementCountRequest) (*GetMeasurementCountResponse, error)
        GetCcReport(context.Context, *GetCcReportRequest) (*GetCcReportResponse, error)
        GetCcMeasurement(context.Context, *GetCcMeasurementRequest) (*GetCcMeasurementResponse, error)
        GetCcEventlog(context.Context, *GetCcEventlogRequest) (*GetCcEventlogResponse, error)
        mustEmbedUnimplementedCimaServer()
}

// UnimplementedCimaServer must be embedded to have forward compatible implementations.
type UnimplementedCimaServer struct {
}

func (UnimplementedCimaServer) GetDefaultAlgorithm(context.Context, *GetDefaultAlgorithmRequest) (*GetDefaultAlgorithmResponse, error) {
        return nil, status.Errorf(codes.Unimplemented, "method GetDefaultAlgorithm not implemented")
}
func (UnimplementedCimaServer) GetMeasurementCount(context.Context, *GetMeasurementCountRequest) (*GetMeasurementCountResponse, error) {
        return nil, status.Errorf(codes.Unimplemented, "method GetMeasurementCount not implemented")
}
func (UnimplementedCimaServer) GetCcReport(context.Context, *GetCcReportRequest) (*GetCcReportResponse, error) {
        return nil, status.Errorf(codes.Unimplemented, "method GetCcReport not implemented")
}
func (UnimplementedCimaServer) GetCcMeasurement(context.Context, *GetCcMeasurementRequest) (*GetCcMeasurementResponse, error) {
        return nil, status.Errorf(codes.Unimplemented, "method GetCcMeasurement not implemented")
}
func (UnimplementedCimaServer) GetCcEventlog(context.Context, *GetCcEventlogRequest) (*GetCcEventlogResponse, error) {
        return nil, status.Errorf(codes.Unimplemented, "method GetCcEventlog not implemented")
}
func (UnimplementedCimaServer) mustEmbedUnimplementedCimaServer() {}

// UnsafeCimaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CimaServer will
// result in compilation errors.
type UnsafeCimaServer interface {
        mustEmbedUnimplementedCimaServer()
}

func RegisterCimaServer(s grpc.ServiceRegistrar, srv CimaServer) {
        s.RegisterService(&Cima_ServiceDesc, srv)
}

func _Cima_GetDefaultAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetDefaultAlgorithmRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(CimaServer).GetDefaultAlgorithm(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: Cima_GetDefaultAlgorithm_FullMethodName,
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(CimaServer).GetDefaultAlgorithm(ctx, req.(*GetDefaultAlgorithmRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _Cima_GetMeasurementCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetMeasurementCountRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(CimaServer).GetMeasurementCount(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: Cima_GetMeasurementCount_FullMethodName,
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(CimaServer).GetMeasurementCount(ctx, req.(*GetMeasurementCountRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _Cima_GetCcReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetCcReportRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(CimaServer).GetCcReport(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: Cima_GetCcReport_FullMethodName,
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(CimaServer).GetCcReport(ctx, req.(*GetCcReportRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _Cima_GetCcMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetCcMeasurementRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(CimaServer).GetCcMeasurement(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: Cima_GetCcMeasurement_FullMethodName,
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(CimaServer).GetCcMeasurement(ctx, req.(*GetCcMeasurementRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _Cima_GetCcEventlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetCcEventlogRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(CimaServer).GetCcEventlog(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: Cima_GetCcEventlog_FullMethodName,
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(CimaServer).GetCcEventlog(ctx, req.(*GetCcEventlogRequest))
        }
        return interceptor(ctx, in, info, handler)
}

// Cima_ServiceDesc is the grpc.ServiceDesc for Cima service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cima_ServiceDesc = grpc.ServiceDesc{
        ServiceName: "cima_server_pb.cima",
        HandlerType: (*CimaServer)(nil),
        Methods: []grpc.MethodDesc{
                {
                        MethodName: "GetDefaultAlgorithm",
                        Handler:    _Cima_GetDefaultAlgorithm_Handler,
                },
                {
                        MethodName: "GetMeasurementCount",
                        Handler:    _Cima_GetMeasurementCount_Handler,
                },
                {
                        MethodName: "GetCcReport",
                        Handler:    _Cima_GetCcReport_Handler,
                },
                {
                        MethodName: "GetCcMeasurement",
                        Handler:    _Cima_GetCcMeasurement_Handler,
                },
                {
                        MethodName: "GetCcEventlog",
                        Handler:    _Cima_GetCcEventlog_Handler,
                },
        },
        Streams:  []grpc.StreamDesc{},
        Metadata: "proto/cima-server.proto",
}
